name: sky_util_app
description: Sky空旅のお供

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3


  # -- Design --
  ### https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.8.1

  ### https://pub.dev/packages/flutter_icons
  flutter_icons: ^1.1.0

  ### https://pub.dev/packages/auto_size_text
  auto_size_text: ^2.1.0

  ### https://pub.dev/packages/progress_indicators
  progress_indicators: ^0.1.5

  ### https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^4.1.2+1


  # -- Provider --
  ### https://pub.dev/packages/provider
  provider: ^4.3.2+2


  # -- Moor --
  ### https://pub.dev/packages/moor
  moor: ^3.3.1

  ### https://pub.dev/packages/sqlite3_flutter_libs
  sqlite3_flutter_libs: ^0.2.0

  ### https://pub.dev/packages/path_provider
  path_provider: ^1.6.18

  ### https://pub.dev/packages/path
  path: ^1.7.0


  # -- Other --
  ### https://pub.dev/packages/intl
  intl: ^0.16.1

  ### https://pub.dev/packages/uuid
  uuid: ^2.2.2

  ### https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.12


dev_dependencies:
  flutter_test:
    sdk: flutter

  ### https://pub.dev/packages/moor_generator
  moor_generator: ^3.3.1

  ### https://pub.dev/packages/build_runner
  build_runner: ^1.10.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/background/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic